Update smallfunction.yaml

diff --git a/.github/workflows/smallfunction.yaml b/.github/workflows/smallfunction.yaml
--- a/.github/workflows/smallfunction.yaml
+++ b/.github/workflows/smallfunction.yaml
@@ -50,7 +50,7 @@ jobs:
       - name: Check image and set variable
         run: |
           calledvar="${{ env.MY_ENV_VAR }}-${{ env.configname }}"
-          check_image=$(echo "$calledvar" | grep "second" || true)
+          check_image=$(echo "$calledvar" | grep "first" || true)
           if [ -n "$check_image" ]; then
           echo "check_image=found" >> $GITHUB_ENV
           else
@@ -60,11 +60,11 @@ jobs:
 
       - name: If check_image is found
         if: ${{ env.check_image == 'found' }}
-        run: echo "The string 'second' was found in the variable."
+        run: echo "The string 'first' was found in the variable."
 
       - name: If check_image is not found
         if: ${{ env.check_image == 'not_found' }}
-        run: echo "The string 'second' was not found in the variable."
+        run: echo "The string 'first' was not found in the variable."
 
          
 
